#!/bin/bash

echo "Running Hugo build..."
hugo

if [ $? -eq 0 ]; then
    echo "Hugo build successful, adding public directory..."
    git add public/
    
    # Check if there are changes to commit in these directories
    if git diff --cached --quiet public/; then
        echo "No changes in public/"
    else
        echo "Changes in public/ have been staged"
    fi
    
    exit 0
else
    echo "Hugo build failed! Aborting commit."
    exit 1
fi